classes
classModelForSMCategorySalesSummary: aClassModel
	#(#id #category #sales_1 #sales_2 #sales_3 #sales_4 #sales_5 #sales_6 #sales_7 #sales_8 #sales_9 #sales_10 #sales_11 #sales_12 #sales_13 #sales_14 #sales_15 #sales_16 #sales_17 #sales_18 #sales_19 #sales_20 #sales_21 #sales_22 #sales_23 #sales_24 #volume1 #volume2 #volume3 #volume4 #volume5 #volume6 #volume7 #volume8 #volume9 #volume10 #volume11 #volume12 #volume13 #volume14 #volume15 #volume16 #volume17 #volume18 #volume19 #volume20 #volume21 #volume22 #volume23 #volume24) do: [ :each |
		aClassModel newAttributeNamed: each ]